# Lab 1 - Introduction to Deep Neural Networks

Nowadays, it is difficult to find someone who has not encountered neural networks in one form or another. Among the most obvious examples, almost everyone has heard of ChatGPT, which is based on large language models (LLMs – Large Language Models), or has used Google Search, which also relies on language models to better understand user queries. However, neural networks are applied in many other fields, such as image recognition, audio analysis, computer games, and even medicine, where they assist in diagnosing diseases. Due to their versatility and rapid development, it is worth learning the basics of how neural networks work and how they can be applied in various domains.

<img src="https://raw.githubusercontent.com/vision-agh/DNN-Course-media/refs/heads/main/lab1_introduction/figures/google.png" alt="Google AI Response" width="600"/>


The aim of these course is to introduce the fundamental concepts related to neural networks, to learn how to use popular libraries for building and training them, such as PyTorch, and to understand the process of machine learning.

During the course, we will explore some of the most popular neural network architectures, such as:
- MLP (Multi-Layer Perceptron)
- CNN (Convolutional Neural Networks)
- RNN (Recurrent Neural Networks)
- GNN (Graph Neural Networks)
- SNN (Spiking Neural Networks)
- Transformers for natural language processing (NLP) as well as computer vision (CV)
- Generative models (GANs, Diffusion Models)
- and others.

We will also cover different machine learning techniques, such as supervised, unsupervised, and reinforcement learning, along with methods like knowledge distillation and transfer learning.

As you can see, the scope of material is very broad, and it is impossible to cover everything within a single semester. However, I hope that by the end of the course you will have a solid foundation for further learning and experimenting with neural networks. 🙂

# What is a deep neural network?

As we can see in the illustration above, which shows feedback generated by Google Gemini, neural networks are systems inspired by the structure and functioning of the human brain. The division into Artificial Intelligence (AI), Machine Learning (ML), Deep Learning (DL), and Generative AI (GAI) is often confusing, but it can be clarified using the diagram below (source: [link](https://commons.wikimedia.org/wiki/File:Unraveling_AI_Complexity_-_A_Comparative_View_of_AI,_Machine_Learning,_Deep_Learning,_and_Generative_AI.png)):

<img src="https://raw.githubusercontent.com/vision-agh/DNN-Course-media/refs/heads/main/lab1_introduction/figures/comparison.png" alt="AI, ML, DL, GAI" width="600"/>

Deep neural networks consist of many interconnected layers. Neurons are organized into layers: the input layer receives the data, hidden layers process it, and the output layer generates the final prediction. Three main elements are essential for training a neural network:

1. **Data** – Neural networks learn from datasets, which provide information about patterns and dependencies.
2. **Architecture** – The structure of the network, i.e. the number of layers, the number of neurons in each layer, type of layers and how they are connected. Different architectures are better suited for different types of tasks.
3. **Learning algorithm** – The method by which the network adjusts its weights and biases based on training data to minimize prediction error. The most commonly used approach is backpropagation, combined with optimizers such as Adam or Stochastic Gradient Descent (SGD).

Based on the type of training data, machine learning can be divided into three main categories:
- **Supervised Learning** – The network learns from labeled data, where each input is paired with a known output (label or value). The goal is to predict correct outputs for unseen data.
- **Unsupervised Learning** – The network learns from unlabeled data, without known outputs. The goal is to discover hidden patterns or structures, such as clustering or dimensionality reduction.
- **Reinforcement Learning** – The network learns through interaction with an environment (simulation), receiving rewards or penalties based on its actions. The goal is to learn optimal decision-making strategies within that environment.

For now, without going into too much detail, I encourage you to explore the following resources:

- https://www.geeksforgeeks.org/machine-learning/supervised-vs-reinforcement-vs-unsupervised/
- https://medium.com/@bensalemh300/supervised-vs-unsupervised-vs-reinforcement-learning-a3e7bcf1dd23
- https://www.youtube.com/watch?v=aircAruvnKk



### Envirenment setup

During the course, we will primarily use Python and the following libraries:

* **PyTorch** ([https://pytorch.org/](https://pytorch.org/)) – a widely used library for building and training neural networks, popular in both academia and industry.
* **PyTorch Geometric** ([https://pytorch-geometric.readthedocs.io/en/latest/](https://pytorch-geometric.readthedocs.io/en/latest/)) – an extension of PyTorch designed for working with graphs and graph neural networks.
* **snnTorch** ([https://snntorch.readthedocs.io/en/latest/](https://snntorch.readthedocs.io/en/latest/)) – a library for building and training spiking neural networks (SNNs).
* **PyTorch Lightning** ([https://www.pytorchlightning.ai/](https://www.pytorchlightning.ai/)) – a high-level interface for PyTorch that simplifies model training and experiment management. We will start using it later in the course.
* **Weights & Biases (W&B)** ([https://wandb.ai/](https://wandb.ai/)) – a tool for experiment tracking, result visualization, and machine learning project management. We will use it for logging our experiments, and it integrates seamlessly with PyTorch Lightning.

Additionally, we will rely on standard data analysis and visualization libraries, such as **NumPy**, **Pandas**, **Matplotlib**, **OpenCV**, and others.
The exercises have been prepared and tested with GPU acceleration using **Jupyter Notebook** and a **Conda virtual environment**. Below is the environment setup guide (for Linux and CUDA 12.8):

```bash
conda create -n dnn python=3.9
conda activate dnn

pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu128
pip3 install torch_geometric
pip3 install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.8.0+cu128.html
pip3 install omegaconf opencv-python matplotlib psutil wandb lightning numba pybind11 tqdm pandas tonic
pip3 install lightning snntorch
```

It is possible that during some classes we will need to install additional libraries; I will inform you about this as needed.
If you do not have access to a GPU or prefer not to run computations on your own machine, you can use **Google Colab** ([https://colab.research.google.com/](https://colab.research.google.com/)), which provides free (but limited) GPU access in the cloud. In that case, you can copy the Jupyter Notebook code into Colab and run it there. However, keep in mind that library version conflicts may occur, so it is recommended to install the required versions manually in a Colab cell when necessary.


## W&B Setup

To use Weights & Biases (W&B) for experiment tracking, you need to create an account on their platform. You can sign up for free at [https://wandb.ai/](https://wandb.ai/). After creating an account, you will receive an API key that you will use to log in from your code (User Settings -> Scroll Down and Reveal API keys).

<img src="https://raw.githubusercontent.com/vision-agh/DNN-Course-media/refs/heads/main/lab1_introduction/figures/api.png" alt="W&B API Key" width="600"/>


During the first run of a script that uses W&B, you will be prompted to enter your API key to authenticate your account. You can also log in directly from a Jupyter Notebook cell using the following command:

```python
!wandb login YOUR_API_KEY
```

from the terminal:

```bash
wandb login YOUR_API_KEY
```

or in Colab:

```python
!pip install wandb
!wandb login YOUR_API_KEY
```

or set the environment variable `WANDB_API_KEY` with your API key:

```python
import os
import wandb

wandb.login()
os.environ['WANDB_API_KEY'] = 'YOUR_API_KEY'
```

All projects and experiments will be organized in W&B dashboard, where you can visualize metrics, compare runs, and manage your machine learning projects. After inviting you to the course project, you will be able to see all the experiments we conduct during the classes under this link: [https://wandb.ai/imperator/deep-neural-network-course](https://wandb.ai/imperator/deep-neural-network-course).

<img src="https://raw.githubusercontent.com/vision-agh/DNN-Course-media/refs/heads/main/lab1_introduction/figures/wandb.png" alt="W&B Dashboard" width="600"/>

# First steps

Let's start by importing the necessary libraries and checking if a GPU is available for computations. If a GPU is not available, the code will automatically fall back to using the CPU. If you are using Google Colab, you can enable GPU support by navigating to `Runtime` -> `Change runtime type` and selecting `GPU` from the `Hardware accelerator` dropdown menu.

In [17]:
import torch

# Check if a GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cpu


Now we can proceed to implement our first neural network layer using PyTorch. We will create a simple feedforward neural network with one hidden layer and demonstrate how to perform a forward pass with some sample input data.

Documentation:
- https://docs.pytorch.org/docs/stable/generated/torch.nn.Linear.html
- https://docs.pytorch.org/docs/stable/generated/torch.randn.html

In [18]:
import torch.nn as nn

# Initialize a simple feedforward neural network layer
# Here, we create a linear layer with 10 input features and 5 output features
# The layer is moved to the appropriate device (GPU or CPU)

layer = nn.Linear(in_features=10, out_features=5, bias=True).to(device)

# We can visualize the layer's variables (learnable parameters):
print("Layer parameters:")
for name, param in layer.named_parameters():
    print(f"{name}: {param.size()}")

# We generate a random input tensor with 10 features and 1 batch size (number of samples)
# We also move this tensor to the appropriate device (same as the layer)

input_tensor = torch.randn(1, 10).to(device)
print("-" * 30)
print("Input tensor:")
print(f"Size: {input_tensor.size()}")

# Perform a forward pass through the layer
output_tensor = layer(input_tensor)
print("-" * 30)
print("Output tensor:")
print(f"Size: {output_tensor.size()}")


Layer parameters:
weight: torch.Size([5, 10])
bias: torch.Size([5])
------------------------------
Input tensor:
Size: torch.Size([1, 10])
------------------------------
Output tensor:
Size: torch.Size([1, 5])


In [19]:
# We can visualize the input and output tensors:
print("Input tensor values:")
print(input_tensor)
print("Output tensor values:")
print(output_tensor)

# Also print the layer's weights and biases
print("Layer weights:")
print(layer.weight)
print("Layer biases:")
print(layer.bias)

Input tensor values:
tensor([[ 1.5292, -0.6293,  0.1639,  1.1357, -1.2346, -1.1306,  1.1617,  0.2351,
         -1.4542, -0.6146]])
Output tensor values:
tensor([[-0.3270, -1.8114, -0.7381,  0.8838, -1.1289]],
       grad_fn=<AddmmBackward0>)
Layer weights:
Parameter containing:
tensor([[ 0.2293,  0.1253,  0.0219, -0.2924, -0.0434,  0.1879,  0.1424,  0.1721,
          0.1058,  0.0913],
        [-0.2366,  0.3053, -0.1480, -0.0356,  0.2369,  0.1731,  0.0897,  0.2435,
          0.3150,  0.2862],
        [ 0.2556,  0.2470,  0.1283, -0.2728,  0.1477,  0.0758, -0.2816, -0.2230,
          0.2055, -0.2686],
        [ 0.0092,  0.0571, -0.2087,  0.2551, -0.2885,  0.1003, -0.0415, -0.1983,
         -0.2325,  0.2049],
        [-0.0148, -0.0940,  0.0878, -0.2881,  0.0586, -0.0789, -0.2643,  0.2426,
          0.2759,  0.0118]], requires_grad=True)
Layer biases:
Parameter containing:
tensor([-0.1072, -0.2320,  0.0966,  0.2901, -0.2110], requires_grad=True)


Below is a simple example of how to use the W&B library to log metrics during training.

In [20]:
import wandb

# Initialize a W&B run
wandb.init(
        project="lab1-introduction",            # do not change this line !
                                                # (this is the name of the project for each lab)

        entity="deep-neural-network-course",    # do not change this line !
                                                # (this is the name of the team for the course)

        group="test_run",                       # do not change this line !
                                                # (this is the name of the group for each lab, e.g. task1, task2, etc.)

        name="Kamil Jeziorek",                  # change to your name
                                                # (e.g. Johny Bravo - your full name)

        settings=wandb.Settings(save_code=False)# do not change this line !
                                                # (this is to avoid saving all the code files in W&B, which would be too large)
)

# Log some example metrics to W&B
for epoch in range(5):
    # Simulate some metrics
    loss = torch.randn(1).item()  # Random loss value
    accuracy = torch.rand(1).item()  # Random accuracy value

    # Log metrics to W&B
    wandb.log({"epoch": epoch, "loss": loss, "accuracy": accuracy})

# Finish the W&B run
wandb.finish()

And you should see the results in your W&B dashboard.

<img src="https://raw.githubusercontent.com/vision-agh/DNN-Course-media/refs/heads/main/lab1_introduction/figures/test.png" alt="W&B Dashboard Example" width="1000"/>

For now, this is enough to get you started. In the next classes, we will delve deeper into the concepts and techniques of deep learning. If you have any questions or need assistance, feel free to ask!